-- AlterTable
ALTER TABLE `indekspengaduan` ADD COLUMN `sla1` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `sla2` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `sla3` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `slagt3` INTEGER NOT NULL DEFAULT 0;
